#!/usr/bin/env python3

import sys, os, utils, addon, printer

def get_args():
    i = 1
    my_arg = []
    while(i < len(sys.argv)):
        my_arg.append(sys.argv[i])
        i += 1
    return my_arg


def main():
    args = get_args()
    addon.chech_date(args[1])
    if (args[0] != "-m" and args[0] != "-f" and args[0] != "-h"):
        print("Bad Argument, use -h for help")
        exit(84)
    if (args[0] == "-h"):
        addon.help()
    else:
        printer.terminal_printer(args[0], args[1])

main()