#!/usr/bin/env python3

import sys, os, utils, addon

def get_args():
    i = 1
    my_arg = []
    while(i < len(sys.argv)):
        my_arg.append(sys.argv[i])
        i += 1
    return my_arg


def main():
    args = get_args()
    if (args[0] == "-h"):
        addon.help()
    else:
        print("lol")

main()